import { useState } from 'react';
import Layout from '../components/Layout';
import RSSFeedInput from '../components/RSSFeedInput';
import ArticleList from '../components/ArticleList';
import FeedList from '../components/FeedList';

const feeds = [
  // Top 30 Tech Feeds
  { name: "TechCrunch", url: "https://techcrunch.com/feed/" },
  { name: "Wired", url: "https://www.wired.com/feed/rss" },
  { name: "The Verge", url: "https://www.theverge.com/rss/index.xml" },
  { name: "Engadget", url: "https://www.engadget.com/rss.xml" },
  { name: "Gizmodo", url: "https://gizmodo.com/rss" },
  { name: "Mashable", url: "https://mashable.com/feed/" },
  { name: "Ars Technica", url: "http://feeds.arstechnica.com/arstechnica/index/" },
  { name: "VentureBeat", url: "https://venturebeat.com/feed/" },
  { name: "Recode", url: "https://www.recode.net/rss/index.xml" },
  { name: "CNET", url: "https://www.cnet.com/rss/all/" },
  { name: "ZDNet", url: "https://www.zdnet.com/news/rss.xml" },
  { name: "TechRadar", url: "https://www.techradar.com/rss" },
  { name: "The Next Web", url: "https://thenextweb.com/feed/" },
  { name: "ReadWrite", url: "https://readwrite.com/feed/" },
  { name: "Slashdot", url: "http://rss.slashdot.org/Slashdot/slashdotMain" },
  { name: "Digital Trends", url: "https://www.digitaltrends.com/feed/" },
  { name: "PCWorld", url: "https://www.pcworld.com/index.rss" },
  { name: "AnandTech", url: "http://www.anandtech.com/rss/" },
  { name: "TechSpot", url: "https://www.techspot.com/backend.xml" },
  { name: "Tom's Hardware", url: "https://www.tomshardware.com/feeds/all" },
  { name: "ExtremeTech", url: "https://www.extremetech.com/feed" },
  { name: "BGR", url: "http://feeds2.feedburner.com/TheBoyGeniusReport" },
  { name: "GigaOM", url: "https://gigaom.com/feed/" },
  { name: "Ubergizmo", url: "https://www.ubergizmo.com/feed/" },
  { name: "9to5Mac", url: "https://9to5mac.com/feed/" },
  { name: "9to5Google", url: "https://9to5google.com/feed/" },
  { name: "Android Authority", url: "https://www.androidauthority.com/feed" },
  { name: "AppleInsider", url: "https://appleinsider.com/rss/news/" },
  { name: "MacRumors", url: "https://www.macrumors.com/macrumors.xml" },
  { name: "TechRepublic", url: "https://www.techrepublic.com/rssfeeds/topic/tech-industry/" },
  // Additional Popular RSS Feeds
  { name: "BBC News", url: "http://feeds.bbci.co.uk/news/rss.xml" },
  { name: "CNN", url: "http://rss.cnn.com/rss/edition.rss" },
  { name: "The New York Times", url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml" },
  { name: "The Guardian", url: "https://www.theguardian.com/world/rss" },
  { name: "Reuters", url: "http://feeds.reuters.com/reuters/topNews" },
  { name: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml" },
  { name: "NPR News", url: "https://www.npr.org/rss/rss.php?id=1001" },
  { name: "The Washington Post", url: "http://feeds.washingtonpost.com/rss/world" },
  { name: "The Wall Street Journal", url: "https://feeds.a.dj.com/rss/RSSWorldNews.xml" },
  { name: "ABC News", url: "https://abcnews.go.com/abcnews/topstories" },
  { name: "CBS News", url: "https://www.cbsnews.com/latest/rss/main" },
  { name: "NBC News", url: "http://feeds.nbcnews.com/nbcnews/public/news" },
  { name: "USA Today", url: "http://rssfeeds.usatoday.com/usatoday-NewsTopStories" },
  { name: "HuffPost", url: "https://www.huffpost.com/section/front-page/feed" },
  { name: "Fox News", url: "http://feeds.foxnews.com/foxnews/latest" },
  { name: "The Independent", url: "https://www.independent.co.uk/news/world/rss" },
  { name: "Bloomberg", url: "https://www.bloomberg.com/feed/podcast/etf-report.xml" },
  { name: "Forbes", url: "https://www.forbes.com/business/feed/" },
  { name: "Fortune", url: "https://fortune.com/feed/" },
  { name: "Financial Times", url: "http://www.ft.com/rss/home/us" },
  { name: "Business Insider", url: "https://www.businessinsider.com/rss" },
  { name: "MarketWatch", url: "https://www.marketwatch.com/rss" },
  { name: "Yahoo Finance", url: "https://finance.yahoo.com/rss" },
  { name: "Economist", url: "https://www.economist.com/rss" },
  { name: "Inc.", url: "https://www.inc.com/rss" },
  { name: "Entrepreneur", url: "https://www.entrepreneur.com/feed" },
  { name: "Fast Company", url: "https://www.fastcompany.com/rss" },
  { name: "Harvard Business Review", url: "https://hbr.org/rss" },
  { name: "MIT Technology Review", url: "https://www.technologyreview.com/feed/" },
  { name: "Scientific American", url: "https://www.scientificamerican.com/feed/" },
  { name: "Nature", url: "https://www.nature.com/nature.rss" },
  { name: "Science Magazine", url: "https://www.sciencemag.org/rss/news_current.xml" },
  { name: "National Geographic", url: "https://www.nationalgeographic.com/rss/" },
  { name: "Smithsonian Magazine", url: "https://www.smithsonianmag.com/rss/" },
  { name: "Popular Science", url: "https://www.popsci.com/rss/" },
  { name: "The Atlantic", url: "https://www.theatlantic.com/feed/all/" },
  { name: "New Yorker", url: "https://www.newyorker.com/feed/all" },
  { name: "Vox", url: "https://www.vox.com/rss/index.xml" },
  { name: "Slate", url: "https://slate.com/feeds/all.rss" },
  { name: "Politico", url: "https://www.politico.com/rss/politicopicks.xml" },
  { name: "Rolling Stone", url: "https://www.rollingstone.com/feed/" },
  { name: "Pitchfork", url: "https://pitchfork.com/rss/reviews/albums/" },
  { name: "Billboard", url: "https://www.billboard.com/rss/" },
  { name: "Variety", url: "https://variety.com/feed/" },
  { name: "The Hollywood Reporter", url: "https://www.hollywoodreporter.com/rss/" },
  { name: "Entertainment Weekly", url: "https://ew.com/feed/" },
  { name: "People", url: "https://people.com/rss/" },
  { name: "TMZ", url: "https://www.tmz.com/rss/" },
  { name: "BuzzFeed", url: "https://www.buzzfeed.com/index.xml" },
  { name: "Gawker", url: "https://www.gawker.com/rss" },
  { name: "The A.V. Club", url: "https://www.avclub.com/rss" },
  { name: "Eater", url: "https://www.eater.com/rss/index.xml" },
  { name: "Bon Appétit", url: "https://www.bonappetit.com/feed/" },
  { name: "Food & Wine", url: "https://www.foodandwine.com/rss" },
  { name: "Saveur", url: "https://www.saveur.com/rss" },
  { name: "Epicurious", url: "https://www.epicurious.com/services/rss/" },
  { name: "Serious Eats", url: "https://www.seriouseats.com/rss" },
  { name: "The Kitchn", url: "https://www.thekitchn.com/rss" },
  { name: "Smitten Kitchen", url: "https://smittenkitchen.com/feed/" },
  { name: "Lifehacker", url: "https://lifehacker.com/rss" },
  { name: "The Simple Dollar", url: "https://www.thesimpledollar.com/feed/" },
  { name: "NerdWallet", url: "https://www.nerdwallet.com/blog/feed/" },
  { name: "The Penny Hoarder", url: "https://www.thepennyhoarder.com/feed/" },
  { name: "Mr. Money Mustache", url: "https://www.mrmoneymustache.com/feed/" },
  { name: "Get Rich Slowly", url: "https://www.getrichslowly.org/feed/" },
  { name: "Financial Samurai", url: "https://www.financialsamurai.com/feed/" },
  { name: "The College Investor", url: "https://thecollegeinvestor.com/feed/" },
  { name: "Good Financial Cents", url: "https://www.goodfinancialcents.com/feed/" },
  { name: "BiggerPockets", url: "https://www.biggerpockets.com/feed/" },
  { name: "The Points Guy", url: "https://thepointsguy.com/rss/" },
  { name: "Nomadic Matt", url: "https://www.nomadicmatt.com/travel-blog/feed/" },
  { name: "The Blonde Abroad", url: "https://theblondeabroad.com/feed/" },
  { name: "Adventurous Kate", url: "https://www.adventurouskate.com/feed/" },
  { name: "Travel Noire", url: "https://travelnoire.com/feed" },
  { name: "Matador Network", url: "https://matadornetwork.com/feed/" },
  { name: "Roads & Kingdoms", url: "https://roadsandkingdoms.com/feed/" },
  { name: "Atlas Obscura", url: "https://www.atlasobscura.com/feed" },
  { name: "Lonely Planet", url: "https://www.lonelyplanet.com/feed" },
  { name: "National Geographic Travel", url: "https://www.nationalgeographic.com/travel/rss" },
];

export default function Home() {
  const [feed, setFeed] = useState(null);

  return (
    <Layout>
      <RSSFeedInput setFeed={setFeed} />
      <FeedList feeds={feeds} setFeed={setFeed} />
      <ArticleList feed={feed} />
    </Layout>
  );
}
